name: Build and run image with QEMU

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install depends
        run: |
          sudo apt update
          sudo apt install gcc-14-x86-64-linux-gnu   \
                      binutils-x86-64-gnu make gdisk \
                      dosfstools grub-pc qemu-system pcre2-utils

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy default config
        run: make config

      - name: Build binaries
        run: make CC=/usr/bin/x86_64-linux-gnu-gcc-14 \
                  LD=/usr/bin/x86_64-gnu-ld           \
                  AR=/usr/bin/x86_64-gnu-ar

      - name: Build image
        run: make image

      - name: Run with QEMU
        run: |
          (./scripts/qemu.sh --no-display --serial-log &> /dev/null &)
          sleep 20 && killall -9 qemu-system-x86_64
          cat serial.log

      - name: 'Run test #1'
        run: ./scripts/test.sh 1

      - name: 'Run test #2'
        run: ./scripts/test.sh 2

      - name: 'Run test #3'
        run: ./scripts/test.sh 3

      - name: 'Run test #4'
        run: ./scripts/test.sh 4

      - name: 'Run test #5'
        run: ./scripts/test.sh 5

      - name: 'Run test #6'
        run: ./scripts/test.sh 6

      - name: 'Run test #7'
        run: ./scripts/test.sh 7

      - name: 'Run test #8'
        run: ./scripts/test.sh 8
